language: objective-c
xcode_workspace: BabysFirst.xcworkspace
xcode_scheme: BabysFirst
xcode_sdk: iphonesimulator
before_script:
  - export LANG=en_US.UTF-8
before_install:
  - gem install cocoapods -v '0.33.1'
  - brew update
  - brew upgrade xctool
